language: node_js

node_js:
  - "10"

addons:
  chrome: stable

script:
  - npm run test -- --configuration=ci
  - npm run e2e -- --configuration=ci

before_deploy:
  - npm run build -- --configuration=production

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
