language: node_js

node_js:
  - "10"

addons:
  chrome: stable

script:
  - npm run test:ci
  - npm run e2e:ci

before_deploy:
  - npm run build:ci

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
